id: P010629
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:17:14.440108
source_metadata:
  id: bdr:W19665
  title: ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེའི་ཞལ་གདམས་སྐོར
  author: ''
  volumes:
    5705bfd50af044ebae64b5144ea3a5d2:
      image_group_id: I1CZ2716
      title: ''
      volume_number: 1
      total_pages: 516
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
