id: IC0CA6CAE
legacy_id: P010629
ocr_import_info:
  bdrc_scan_id: W19665
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T15:46:20'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T15:33:21.229099+00:00'
last_modified: 2022-08-30 23:33:49.875394
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W19665
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW19665
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེའི་ཞལ་གདམས་སྐོར།
  author: ཨ་འཛོམ་འབྲུག་པ་འགྲོ་འདུལ་དཔའ་བོ་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.6823157201293719
  ocr_word_median_confidence_index: 0.7300000190734863
quality: null
bases:
  I1CZ2716:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2716
      total_pages: 516
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2716.txt
    statistics:
      ocr_word_median_confidence_index: 0.7300000190734863
      ocr_word_mean_confidence_index: 0.6823157201293719
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
